### ISSUE TITLE
[Suggestion] Also count AUR package updates towards the total update count

### ISSUE THREAD

**Issue by moritz-john** [bouteillerAlan/archupdate#10]
Hello,

My recommendation is to incorporate AUR package updates into the total count of available package updates. Based on my research, this can be accomplished. 

As indicated in [this discussion](https://github.com/Jguer/yay/issues/1350), you can obtain the number of available AUR package updates by using the AUR helper [yay](https://github.com/Jguer/yay) and executing the command `yay -Qua`.

This can be integrated into your existing process, similar to how you are currently utilizing [`checkupdates`](https://github.com/bouteillerAlan/archupdate/blob/be729cdfcf891f46ce0cd0175ef2aa56166cc81d/a2n.archupdate.plasmoid/contents/service/Updater.qml#L14C3-L16C4). For example:

```
  function count() {
    cmd.exec("yay -Qua | wc -l")
  }
```
The resulting count of AUR updates can be added to the count obtained from the standard `checkupdates | wc -l` command.

___

My suggestion would be:
Add a text field e.g. "AUR update count command" in the settings, so that people could add the command needed for their specific AUR helper. 
**OR**
A checkbox for the most commonly used AUR helper e.g. yay & [paru](https://github.com/Morganamilo/paru)
**OR**
Offer both a checkbox and a text field to demonstrate the command syntax in the text field without enabling the setting by default.

(The command for paru should be `paru -Qua` / `paru -Qua | wc -l`)

____
It's important to note that not all users may be using the AUR or the same AUR helper, but it could be reasonable to consider including options for the two most commonly used ones, yay and paru.

Kind regards and thank you for your work.

**Comment by moritz-john** [comment]
Upon further consideration, an alternative approach may be taken.
Instead of "adding" `checkupdates` & `yay -Qua` one could just call `yay -Qu`.

`yay -Qu` lists all available package updates including AUR ones.

I'd imagine that different AUR helpers offer a similar operation.

___

Maybe this would make the implementation of this feature easier since one would only offer an option to replace `checkupdates` with something else.

![image](https://github.com/bouteillerAlan/archupdate/assets/70295002/cfe677b1-6638-4549-ac43-b26fd064b1fc)
(green arrow highlights an AUR package)

**Comment by bouteillerAlan** [comment]
Yeah, think it's a good idea to provide the count via only one command. I'm going to add an option to customize the command.

The problem is that `yay -Qu` doesn't sync db while `checkupdates` does. As a result, `yay -Qu` result is wrong unless a sync is performed first.

![image](https://github.com/bouteillerAlan/archupdate/assets/30547569/f53bfbc5-7790-4f59-81f0-35c2b8203082)

So I certainly have to do `(checkupdates && yay -Qua) | wc -l`, for triggering the sync safely. I prefer to use `checkupdates` rather than `yay` or `paru` for sync.

**Comment by luisbocanegra** [comment]
If this is implemented I think it could be useful to display somewhere in the widget how many updates are from the AUR, I was thinking of something like `34+2` in the badge but that may get really long so probably in the tooltip.

**Comment by bouteillerAlan** [comment]
#14

**Comment by moritz-john** [comment]
> So I certainly have to do `(checkupdates && yay -Qua) | wc -l`, for triggering the sync safely. I prefer to use `checkupdates` rather than `yay` or `paru` for sync.

Quick question. Does archupdate always use Bash in the background? 
Or can it be forced to execute all those commands via Bash?

I am asking since I am using Fish Shell in Konsole and the syntax `(checkupdates && yay -Qua) | wc -l` would not work in Fish:


![image](https://github.com/bouteillerAlan/archupdate/assets/70295002/4f052ba8-28fa-4d74-90a4-0cfae87365bb)

I guess I am asking if the commands are executed with a shebang like `#!/bin/bash`.

**Comment by bouteillerAlan** [comment]
> If this is implemented I think it could be useful to display somewhere in the widget how many updates are from the AUR, I was thinking of something like `34+2` in the badge but that may get really long so probably in the tooltip.

Yeah I thought about it, I'll see if I can do it this weekend. Maybe with some customization options.

Some ideas : 
 - the user can choose to put a separator between the two totals (eg. 2+34 or 2/34 or 2 34)
- user can choose to add totals (36)
- user can choose between tooltip and badge (or both ?)

**Comment by bouteillerAlan** [comment]
> > So I certainly have to do `(checkupdates && yay -Qua) | wc -l`, for triggering the sync safely. I prefer to use `checkupdates` rather than `yay` or `paru` for sync.
> 
> Quick question. Does archupdate always use Bash in the background? Or can it be forced to execute all those commands with Bash?
> 
> I am asking since I am using Fish Shell in Konsole and the syntax `(checkupdates && yay -Qua) | wc -l` would not work in Fish:
> 
> ![image](https://user-images.githubusercontent.com/70295002/280273305-4f052ba8-28fa-4d74-90a4-0cfae87365bb.png)
> 
> I guess I am asking if the commands are executed with a shebang like `#!/bin/bash`.
> 
> EDIT: My system is still using Bash for everything - I am just using Fish in Konsole.

The command executed for the counting doesn't use konsole but [`PlasmaCore.DataSource`](https://api.kde.org/frameworks/plasma-framework/html/classPlasma_1_1DataSource.html). Konsole is used for the update command: `konsole -e 'yay'` so it exec with the program setup in konsole if I'm not wrong.

**Comment by luisbocanegra** [comment]
> > If this is implemented I think it could be useful to display somewhere in the widget how many updates are from the AUR, I was thinking of something like `34+2` in the badge but that may get really long so probably in the tooltip.
> 
> Yeah I thought about it, I'll see if I can do it this weekend. Maybe with some customization options.
> 
> Some ideas :
> 
>     * the user can choose to put a separator between the two totals (eg. 2+34 or 2/34 or 2 34)
> 
>     * user can choose to add totals (36)
> 
>     * user can choose between tooltip and badge (or both ?)

Yeah, in the tooltip something like `There are x updates (x from AUR)` or something like that

**Comment by luisbocanegra** [comment]
> > Quick question. Does archupdate always use Bash in the background? Or can it be forced to execute all those commands with Bash?
> > I am asking since I am using Fish Shell in Konsole and the syntax `(checkupdates && yay -Qua) | wc -l` would not work in Fish:
> > ![image](https://user-images.githubusercontent.com/70295002/280273305-4f052ba8-28fa-4d74-90a4-0cfae87365bb.png)
> > I guess I am asking if the commands are executed with a shebang like `#!/bin/bash`.
> > EDIT: My system is still using Bash for everything - I am just using Fish in Konsole.
> 
> The command executed for the counting doesn't use konsole but [`PlasmaCore.DataSource`](https://api.kde.org/frameworks/plasma-framework/html/classPlasma_1_1DataSource.html). It call [that](https://github.com/KDE/plasma-workspace/tree/master/dataengines/executable?rgh-link-date=2023-11-03T12%3A27%3A03Z).

Just checked running `echo $0` from it and it returns `/bin/sh` so is either POSIX shell (Bourne Shell) or, more commonly, an alias to Bash (improved Bourne Shell) in most systems. My login shell is zsh so it doesn't seem to depend on that.

**Comment by bouteillerAlan** [comment]
Done in #13
