### ISSUE TITLE
[Suggestion] Add "Arch update counter" to the AUR

### ISSUE THREAD

**Issue by moritz-john** [bouteillerAlan/archupdate#20]
First of all thank you for implementing https://github.com/bouteillerAlan/archupdate/issues/10 :+1: !

Another suggestion is to add the widget to the AUR similar to other applets: https://aur.archlinux.org/packages?K=plasmoid&SB=p

___

I am suggesting this because as I wanted to update the widget to the newest version, pling.com is down once again:
![image](https://github.com/bouteillerAlan/archupdate/assets/70295002/1826dac4-4c12-4b48-90e5-97768ac4e49a)

Another benefit is that as far as I know there is no way to automatically update widgets downloaded through KDE / pling but the AUR would do exactly that. 

Kind regards
Moritz

**Comment by bouteillerAlan** [comment]
#21

**Comment by olib14** [comment]
>no way to automatically update widgets downloaded through KDE / pling

Discover handles updates for widgets downloaded and installed through Get New....

**Comment by bouteillerAlan** [comment]
> > no way to automatically update widgets downloaded through KDE / pling
> 
> Discover handles updates for widgets downloaded and installed through Get New....

Ho ? You sure about that ? :open_mouth: I've always needed (or felt?) to uninstall the applet and reinstall it to update it.

**Comment by olib14** [comment]
It really should do, but I haven't always found it reliable. It seems to take a while to figure out there's an update, and might need manual checking. A few plasmoids do offer AUR versions such as syncthingtray, or everything `plasma5-applets-*`.

**Comment by moritz-john** [comment]
_Disclaimer: I have little to no experience in creating PKGBUILDs and I attempted to do so with limited success._

I made an attempt to create a PKGBUILD on my own but encountered some difficulties. I drew inspiration from [this existing PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma-applet-custom-notifier). However, my efforts were not successful:

```
pkgname=plasma-applet-archupdate
pkgver=1.0
pkgrel=1
pkgdesc="Arch update counter - plasma widget"
arch=('any')
url="https://github.com/bouteillerAlan/archupdate.git"
license=('GPL')
depends=('plasma-workspace' 'pacman-contrib' 'konsole')
source=("https://github.com/bouteillerAlan/archupdate/tree/ba98fb42d7987bef16589b4ff4c9004c96cc2286/a2n.archupdate.plasmoid")
md5sums=('SKIP')

package() {
    mkdir -p "$pkgdir/usr/share/plasma/plasmoids/org.kde.plasma.custom-archupdate"
    cp "${srcdir}/a2n.archupdate.plasmoid" "$pkgdir/usr/share/plasma/plasmoids/org.kde.plasma.custom-archupdate"
}
```
```
makepkg
makepkg --install
```
![image](https://github.com/bouteillerAlan/archupdate/assets/70295002/0cba43d2-db57-4b3b-96ce-6834e8e576cb)
I guess `a2n.archupdate.plasmoid` gets installed at the correct location but it's contents are completly wrong.

___

Maybe @bouteillerAlan can improve on my failed attempt or learn something from it.
Also I think hardcoding so many things in the PKGBUILD is wrong.
Furthermore I'd need to actually calculate the md5sum instead of skipping it.
On top of that I don't know how that PKGBUILD would handle potential updates.

**Comment by bouteillerAlan** [comment]
> It really should do, but I haven't always found it reliable. It seems to take a while to figure out there's an update, and might need manual checking. A few plasmoids do offer AUR versions such as syncthingtray, or everything `plasma5-applets-*`.

Ho ok :+1:

**Comment by bouteillerAlan** [comment]
> _Disclaimer: I have little to no experience in creating PKGBUILDs and I attempted to do so with limited success._
> 
> I made an attempt to create a PKGBUILD on my own but encountered some difficulties. I drew inspiration from [this existing PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma-applet-custom-notifier). However, my efforts were not successful:
> 
> ```
> pkgname=plasma-applet-archupdate
> pkgver=1.0
> pkgrel=1
> pkgdesc="Arch update counter - plasma widget"
> arch=('any')
> url="https://github.com/bouteillerAlan/archupdate.git"
> license=('GPL')
> depends=('plasma-workspace' 'pacman-contrib' 'konsole')
> source=("https://github.com/bouteillerAlan/archupdate/tree/ba98fb42d7987bef16589b4ff4c9004c96cc2286/a2n.archupdate.plasmoid")
> md5sums=('SKIP')
> 
> package() {
>     mkdir -p "$pkgdir/usr/share/plasma/plasmoids/org.kde.plasma.custom-archupdate"
>     cp "${srcdir}/a2n.archupdate.plasmoid" "$pkgdir/usr/share/plasma/plasmoids/org.kde.plasma.custom-archupdate"
> }
> ```
> 
> ```
> makepkg
> makepkg --install
> ```
> 
> ![image](https://user-images.githubusercontent.com/70295002/281151916-0cba43d2-db57-4b3b-96ce-6834e8e576cb.png) I guess `a2n.archupdate.plasmoid` gets installed at the correct location but it's contents are completly wrong.
> 
> Maybe @bouteillerAlan can improve on my failed attempt or learn something from it. Also I think hardcoding so many things in the PKGBUILD is wrong. Furthermore I'd need to actually calculate the md5sum instead of skipping it. On top of that I don't know how that PKGBUILD would handle potential updates.

I'm on my way of doing it on #21, if you want a little example I have made an article about that [just here](https://medium.com/@a2nb/submitting-a-package-to-the-aur-e9117d07494d).

The main difference between the article and here is that I want to use the git repository for handling the last release in my PKGBUILD file, so it's a little bit more complicated (imo).

**Comment by olib14** [comment]
You could consider the use of CMake to install the plasmoid:

e.g. https://invent.kde.org/olib/thermalmonitor/-/blob/master/CMakeLists.txt

Not really necessary though, this is generally what KDE's own plasmoids use because they're embedded in CMake projects.

@moritz-john That's definitely not a .plasmoid, but some JSON returned from GitHub. A .plasmoid file is simply a renamed .zip containing a folder 'package' which has 'metadata.json' and a folder 'contents'.

**Comment by moritz-john** [comment]
> I'm on my way of doing it on #21, if you want a little example I have made an article about that [just here](https://medium.com/@a2nb/submitting-a-package-to-the-aur-e9117d07494d).
> 
> The main difference between the article and here is that I want to use the git repository for handling the last release in my PKGBUILD file, so it's a little bit more complicated (imo).

Oh, I guess you absolutely don't need any help then :smile:!
Thanks for the article.
___
(Please just ignore my attempt at this.)

**Comment by bouteillerAlan** [comment]
Hey attempt is good for learning and I'm still a noob in this PKGBUILD stuff haha :smile: 

Don't know for CMake, can I just do an `install` of `a2n.archupdate.plasmoid` into ~/.local/share/plasma/plasmoid ?

**Comment by olib14** [comment]
I think you may need to extract the contents of the archive, I'm not entirely sure and am away from my computer for a short while. I recommend releasing a .plasmoid file and using that in both the KDE Store and AUR though, that'd be easiest.

________________________________

**Comment by moritz-john** [comment]
> into ~/.local/share/plasma/plasmoid ?

That was my first idea as well but I did not see any other PKGBUILD doing that.

Most [plasma5-applets-*](https://aur.archlinux.org/packages?O=0&SeB=nd&K=plasma5-applet&outdated=&SB=p&SO=d&PP=50&submit=Go) I looked at use `/usr/share/plasma/plasmoids/` e.g.: 

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma5-applets-latte-separator

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma5-applets-flipweather

**Comment by olib14** [comment]
The latter is correct - we are installing a plasmoid got the system. Plasmoids installed at the user level are meant to be managed by them, through Get New Stuff for example.

**Comment by bouteillerAlan** [comment]
> The latter is correct - we are installing a plasmoid for the system. Plasmoids installed at the user level are meant to be managed by them, through Get New Stuff for example.

Ho yes, good call, I tend to forget things sometimes :laughing:

**Comment by bouteillerAlan** [comment]
I think `cmake` is used because `install` is not made for moving folders with files in it.

`install` can create a complex folder tree, but he can only move one file at a time.

So `cmake` is used to create a package and, then, install the package into the right place.

But I wonder if a cmd like that could work : `find directory/tree/to/copy -type f -exec install -Dm 755 "{}" "target/directory/{}" \;`

**Comment by olib14** [comment]
There should be a way to extract the plasmoid archive and install the contents. Pling is back up, by the way, it was victim of a DDoS attack earlier.

**Comment by olib14** [comment]
I can't find an example of a PKGBUILD that uses the .plasmoid as a source, most seem to download the git archive and use that. It also seems fine to use `cp -r package/* "$pkgdir/usr/share/plasma/plasmoids/PLASMOIDNAME/"`, for example: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma5-applets-fokus

**Comment by bouteillerAlan** [comment]
Yes, the usage of the git repository is very cool because I don't need to update so much think in the PKGBUILD file if I made an update :)

**Comment by moritz-john** [comment]
I got my PKGBUILD working. It's still based on [this](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plasma-applet-custom-notifier).
___
I created a fork of archupdate and implemented a Github workflow that packages only the folder `a2n.archupdate.plasmoid` as a ZIP, lets you select a version tag and automatically creates the release for you:

https://github.com/moritz-john/archupdate/blob/main/.github/workflows/zip_and_release.yml
___

Next I modified my PKGBUILD:
```
pkgname=plasma-applet-archupdate
pkgver=1.0
pkgrel=1
pkgdesc="Arch update counter - plasma widget"
arch=('any')
url="https://github.com/bouteillerAlan/archupdate"
license=('GPL')
depends=('plasma-workspace' 'pacman-contrib' 'konsole')
source=("https://github.com/moritz-john/archupdate/releases/download/v4.2/archupdate.zip")
md5sums=('SKIP')

package() {
    rm archupdate.zip

    mkdir -p "$pkgdir/usr/share/plasma/plasmoids/org.kde.plasma.custom-archupdate"
    cp -r * "$pkgdir/usr/share/plasma/plasmoids/org.kde.plasma.custom-archupdate"
}
```
Now `makepgk` & `makepgk --install` sucesfully install all the files in the right directory and I get a working widget:

![image](https://github.com/bouteillerAlan/archupdate/assets/70295002/3806fe6f-e4e5-4899-bff5-4ae51ac49f40)

**Comment by olib14** [comment]
Remember to use pkgver in the source URL.

**Comment by bouteillerAlan** [comment]
Yup, but I prefer to use install instead of cp just to ensure permissions are correct :) 
I'have my own PKGBUILD that are mostly finish in the #21 branch if you want to look.

**Comment by bouteillerAlan** [comment]
In your PKGBUILD you use a tarball file and not a git process. So you need to use `$pkgver` like olib say. And you need to execute `makepkg -g >> PKGBUILD` in place of the `SKIP` for checking that the file checksum are correct.

**Comment by bouteillerAlan** [comment]
If you use a git process (like in #21) you have to create (in a perfect world) a signed git tag with your gpg and check that the tag you use is signed with your key

**Comment by moritz-john** [comment]
Thanks for the suggestions, but my attempt was just a quick and dirty prototype.
Since you already have an almost working solution anyways I'll delete my fork again.

**Comment by bouteillerAlan** [comment]
> Thanks for the suggestions, but my attempt was just a quick and dirty prototype. Since you already have an almost working solution anyways I'll delete my fork again.

Hey no problem :) If you want to experiment you can run the QA process ([describe here](https://medium.com/@a2nb/submitting-a-package-to-the-aur-e9117d07494d#0321)) and use your own PKGBUILD in local, just for fun :D 

I'm happy if we can share knowledge ^^

**Comment by bouteillerAlan** [comment]
#21 merge, I just need to push on the aur and I can close this ticket :)

**Comment by bouteillerAlan** [comment]
Done https://aur.archlinux.org/packages/kdeplasma-arch-update-notifier-git

**Comment by moritz-john** [comment]
@bouteillerAlan 
```
[...]
:: (1/1) Parsing SRCINFO: kdeplasma-arch-update-notifier-git
gpg: error reading key: No public key

 :: PGP keys need importing:
 -> 6A2ECC8A396F8A943A109A1E0F11C2A6BF79111E, required by: kdeplasma-arch-update-notifier-git
:: Import? [Y/n] 
:: Importing keys with gpg...
gpg: keyserver receive failed: No data
 -> problem importing keys
```

I get this error when trying to install the package. 
I can install your other package `dracut-numlock 1.0.1-1` without any errors though.

___
I tried to use `gpg --refresh-keys` & `gpg --keyserver keyserver.ubuntu.com --recv-keys 6A2ECC8A396F8A943A109A1E0F11C2A6BF79111E`.

Any idea how to fix this? Or do you need to follow [this step](https://wiki.archlinux.org/title/GnuPG#Sending_keys) first?

Kind regards,
Moritz

**Comment by bouteillerAlan** [comment]
> @bouteillerAlan
> 
> ```
> [...]
> :: (1/1) Parsing SRCINFO: kdeplasma-arch-update-notifier-git
> gpg: error reading key: No public key
> 
>  :: PGP keys need importing:
>  -> 6A2ECC8A396F8A943A109A1E0F11C2A6BF79111E, required by: kdeplasma-arch-update-notifier-git
> :: Import? [Y/n] 
> :: Importing keys with gpg...
> gpg: keyserver receive failed: No data
>  -> problem importing keys
> ```
> 
> I get this error when trying to install the package. I can install your other package `dracut-numlock 1.0.1-1` without any errors though.
> 
> I tried to use `gpg --refresh-keys` & `gpg --keyserver keyserver.ubuntu.com --recv-keys 6A2ECC8A396F8A943A109A1E0F11C2A6BF79111E`.
> 
> Any idea how to fix this? Or do you need to follow [this step](https://wiki.archlinux.org/title/GnuPG#Sending_keys) first?
> 
> Kind regards, Moritz

Ha god dammit. Hum. I have made a fix can you retry ?

**Comment by moritz-john** [comment]
EDIT: Fixed by manually creating a file with the content of your key https://github.com/bouteillerAlan.gpg and importing that file via `gpg --import /path/to/key.asc`.

I think you need to follow something like https://wiki.archlinux.org/title/GnuPG#Sending_keys

**Comment by bouteillerAlan** [comment]
@moritz-john can you retry without the key imported manually ? I think I have forgoten the pgp file (checked on another package like [gitea](https://gitlab.archlinux.org/archlinux/packaging/packages/gitea)), it's added now

**Comment by moritz-john** [comment]
> @moritz-john can you retry without the key imported manually ? I think I have forgoten the pgp file (checked on another package like [gitea](https://gitlab.archlinux.org/archlinux/packaging/packages/gitea)), it's added now

I just tried on a EndeavourOS live USB:
![Screenshot_2023-11-08_17-42-04](https://github.com/bouteillerAlan/archupdate/assets/70295002/a58fa134-3ce3-4c7d-9dc5-7cf6d95b6fcd)

and it's still not working.
I think you need to follow this section: https://wiki.archlinux.org/title/GnuPG#Sending_keys but I am not sure myself.

**Comment by moritz-john** [comment]
I also tried on my system again, after removing your key:
```
❯ gpg --delete-keys 6A2ECC8A396F8A943A109A1E0F11C2A6BF79111E
gpg (GnuPG) 2.2.41; Copyright (C) 2022 g10 Code GmbH
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


pub  rsa4096/0F11C2A6BF79111E 2023-03-30 Bouteiller [a2n] Alan <a2n.dev@pm.me>

Delete this key from the keyring? (y/N) y

~ took 4s 

❯ yay -S kdeplasma-arch-update-notifier-git
Please touch the device.
AUR Explicit (1): kdeplasma-arch-update-notifier-git-4.2.1-1
:: PKGBUILD up to date, skipping download: kdeplasma-arch-update-notifier-git
  1 kdeplasma-arch-update-notifier-git (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 kdeplasma-arch-update-notifier-git (Installed) (Build Files Exist)
==> PKGBUILDs to edit?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: kdeplasma-arch-update-notifier-git 4.2.1-1 (Mi 08 Nov 2023 17:46:57 CET)
==> Retrieving sources...
  -> Updating archupdate git repo...
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    archupdate ... Skipped
:: (1/1) Parsing SRCINFO: kdeplasma-arch-update-notifier-git
gpg: error reading key: No public key

 :: PGP keys need importing:
 -> 6A2ECC8A396F8A943A109A1E0F11C2A6BF79111E, required by: kdeplasma-arch-update-notifier-git
:: Import? [Y/n] 
:: Importing keys with gpg...
gpg: keyserver receive failed: No data
 -> problem importing keys

~ took 8s 
❯ 
```

**Comment by bouteillerAlan** [comment]
okai i'm trying rn, keep you in touch if I find the problem

**Comment by bouteillerAlan** [comment]
Ok it should work now :)

**Comment by moritz-john** [comment]
> Ok it should work now, the push to a pgp server is mandatory ^^

I can confirm, it works now :tada:.
Thank you for your work! :)
