### ISSUE TITLE
[Suggestion] Hide the Icon when no updates are available and "Shown when relevant" is selected 

### ISSUE THREAD

**Issue by BSerpent86** [bouteillerAlan/archupdate#28]
Like the title says, when selecting "Shown when relevant" in the System Tray Settings, it would be great if the icon is hidden and when updates are available, is shown automatically until updates are done.

**Comment by bouteillerAlan** [comment]
Release in https://github.com/bouteillerAlan/archupdate/releases/tag/v5.1.0
