### ISSUE TITLE
A feature suggestion: When updates are available, left-click will drop a menu with a list of  available package to be updated

### ISSUE THREAD

**Issue by Mshmaitelly** [bouteillerAlan/archupdate#37]
I am certain I saw this feature before. Maybe it was part of a forked version of this plasmoid.
A feature suggestion: When updates are available, left-click will drop a menu with a list of available package to be updated
Is there a way, if the user would click on the drop-down menu entry of a package to be updated, a short description of what are the changes in the new update?

**Comment by bouteillerAlan** [comment]
Hey, yes someone made a version with that :) 

atm we have the following action : 

- left or middle click > check the update
- left or middle click > launch the update
- right click is reserved for the system menu

So it's a good idea for a feature, but I don't know how to implement it without losing a feature, I need to think about it ^^ 
Any idea maybe ?

**Comment by Mshmaitelly** [comment]
Left click > check for update
middle clik > do check for update and do  install the updates.

Thanks,
Mahmoud A Shmaitelly
BE (CCE) ME (CCE)
Ph.D. Studies (Microelectronics and Photonics)
Principal DV Solutions Architect
469-865-0613
 

    On Sunday, March 10, 2024 at 04:34:32 PM CDT, A2N ***@***.***> wrote:  
 
 


Hey, yes someone made a version with that :)

atm we have the following action :
   
   - left or middle click > check the update
   - left or middle click > launch the update
   - right click is reserved for the system menu

So it's a good idea for a feature, but I don't know how to implement it without losing a feature, I need to think about it ^^
Any idea maybe ?

**Comment by Maryse47** [comment]
> atm we have the following action :
> 
>     left or middle click > check the update
>     left or middle click > launch the update
>     right click is reserved for the system menu

What about showing list when mouse cursor hover over plasmoid icon?
Right now when hovering over icon it shows the package number count but instead it could show a list of packages (it can be trimmed when there are a lot of them).

**Comment by Mshmaitelly** [comment]
Good idea.

Yahoo Mail: Search, Organize, Conquer 
 
  On Tue, Mar 12, 2024 at 8:10 AM, ***@***.***> wrote:   



atm we have the following action :
left or middle click > check the update
left or middle click > launch the update
right click is reserved for the system menu


What about showing list when mouse cursor hover over plasmoid icon?
Right now when hovering over icon it shows the package number count but instead it could show a list of packages (it can be trimmed when there are a lot of them).

**Comment by bouteillerAlan** [comment]
Yeah, I thought about that, but I need to check if it's possible to add a scrollbar in it

**Comment by Maryse47** [comment]
Alternatively you may do:

-  left or middle click > show update list alongside update/check update buttons (same as shown in the screenshot above.)

**Comment by bouteillerAlan** [comment]
link to #48

**Comment by bouteillerAlan** [comment]
![allalt](https://github.com/bouteillerAlan/archupdate/assets/30547569/1a5dcf1b-eeb5-4cc8-8296-116dd5e3fe74)
Close in #48

**Comment by Maryse47** [comment]
It looks really great ,thx!
