### ISSUE TITLE
Make default mouse click action configurable (or reverse them)

### ISSUE THREAD

**Issue by Maryse47** [bouteillerAlan/archupdate#41]
Currently the default action for single click is _refresh_ and for middle click it's _update_. For me the more natural choice would be to reverse those (single - update, middle - refresh).

I don't know if other users prefer the current state but would it be possible to at least make this configurable?

**Comment by bouteillerAlan** [comment]
Hi, yes it's possible. I tried to do it today :)

**Comment by bouteillerAlan** [comment]
Very simple switch release in https://github.com/bouteillerAlan/archupdate/releases/tag/v5.1.0

**Comment by Maryse47** [comment]
Thx, it works great.
