### ISSUE TITLE
[Suggestion] Make it actually update?

### ISSUE THREAD

**Issue by jmfergeau** [bouteillerAlan/archupdate#5]
Having an update counting is pretty rad, i needed it.

But why not making it actually update? For instance, with a context menu "update" that would do by default "sudo pacman -Syu" in the user's console (with the option to custom the console and the command in the settings)

Hope that helps. ^^

**Comment by bouteillerAlan** [comment]
wip #6

**Comment by bouteillerAlan** [comment]
Release on pling today : https://www.pling.com/p/1940819/
