### ISSUE TITLE
"Install all update" button in list view doesn't work

### ISSUE THREAD

**Issue by Maryse47** [bouteillerAlan/archupdate#50]
When I open the new package list view then clicking on _Install all update_ button does nothing. Everything else seems to work correctly:

- Update buttons for specific packages work
- Refresh button work
- Update button from right click menu work
- Update by left/middle click on tray icon work

The _Install all update_ button is the only thing that results in no action after click.

**Comment by bouteillerAlan** [comment]
Need to update the name of [this function](https://github.com/bouteillerAlan/archupdate/blob/bda16bd25320f45ef6f9707b2940b08294bab934/a2n.archupdate.plasmoid/contents/ui/Full.qml#L27) because `update` seem reserved, `updateAll` work.
I'm doing that soon.

**Comment by bouteillerAlan** [comment]
Should be fix with the latest release :)
