### ISSUE TITLE
yay keeps spawning after refreshing list

### ISSUE THREAD

**Issue by Qweffe** [bouteillerAlan/archupdate#51]
when i manually refresh list new yay processes will keep spawning bogging down my laptop, when i execute `yay -Qua
` manually it works fine
![obrazek](https://github.com/bouteillerAlan/archupdate/assets/105426376/888d2570-5607-435a-b627-37bf49f27405)

**Comment by bouteillerAlan** [comment]
Wondering if it's not link to #49. I have tested both on my laptop and I have no problem except if I spam the refresh button like a mad man. Perhaps we should add a function that waits for the current refresh to finish before starting another.

@Qweffe Does the process end at some point or not?

**Comment by bouteillerAlan** [comment]
Like I said, the problem appears only when I spam the refresh button. I have added some code to kind of prevent that. I close the issue. 

Feel free to reopen the issue only if : 
- when you click one time on the refresh button multiple yay instance appear and none of them closed after a certain moment
