### ISSUE TITLE
Updates not counted correctly

### ISSUE THREAD

**Issue by neuromante** [bouteillerAlan/archupdate#52]
Arch + AUR GIT build
Screenshot is self-explanatory
![Schermata_20240314_100414](https://github.com/bouteillerAlan/archupdate/assets/384874/d056784c-fc0d-4566-9c76-5f2a2ab89640)
Thank You

**Comment by bouteillerAlan** [comment]
Hello @neuromante, does the bug appear only on the first launch or not?
 
first launch = when you install the widget and add it into the plasma bar or into the systray without any other action, like a click on the refresh button

**Comment by neuromante** [comment]
Hi, I’ve reloaded my plasma desktop two or three times already with the widget installed and I get always the same resultThanksLorenzo Nizzi Grifi Gargiolli - Studio Legale Piazza Indipendenza 21 - 50129 - FirenzeTel ***@***.*** giorno 14 mar 2024, alle ore 16:23, A2N ***@***.***> ha scritto:﻿
Hello @neuromante, does the bug appear only on the first launch or not?
first launch = when you install the widget and add it into the plasma bar or into the systray without any other action, like a click on the refresh button

**Comment by bouteillerAlan** [comment]
Hey @neuromante could you check if the latest release fixed the issues ?

**Comment by neuromante** [comment]
![Schermata_20240315_165155](https://github.com/bouteillerAlan/archupdate/assets/384874/d25120b6-6757-46b6-9f68-20667fe05055)

**Comment by bouteillerAlan** [comment]
Hey @neuromante can you try the v6.1.5 and tell me if the problem persists ? (the pling store & aur are up-to-date)

Check if you are in the right version via the settings window : 
![image](https://github.com/bouteillerAlan/archupdate/assets/30547569/6d10930c-d73c-4249-9d7a-9d022580bd1d)

**Comment by neuromante** [comment]
Still a bit slow to get the updates but the issue seems to be fixed :) Nice job!
