### ISSUE TITLE
Here's my PKGBUILD

### ISSUE THREAD

**Issue by claymorwan** [bouteillerAlan/archupdate#68]
I'm trying to port sgdboop on the aur (there's only a bin version which doesn't seem to work)
Since it's not a plasma thingy I don't think I need the plasma parts of the code
```
# Maintainer: claymorwan <claymorw@gmail.com>

_tag=8a3d5dd5a815a4234634a02b5bc3186821d6862c
_sourceName="SGDBoop"

pkgname="sgdboop"
pkgver=1.2.8
pkgrel=1
pkgdesc="SGDBoop is a tool that automatically applies assets from SteamGridDB directly to your Steam library with a click of a button, removing the need to download and set them manually. Originally made by steamgriddb.com"
arch=("any")
url="https://github.com/SteamGridDB/SGDBoop"
license=('zlib')
depends=()
makedepends=()
optdepends=()
source=("git+${url}.git#tag=${_tag}?signed")
md5sums=("SKIP")
validpgpkeys=("CC5E1DF06FB78249")

pkgver() {
	cd "${_sourceName}"
	git describe --tags | sed 's/^v//'
}

package() {
	cd "${_sourceName}"
	install -Dm 644 LICENSE -t "${pkgdir}"/usr/share/licenses/"${pkgname}"
}
```

**Comment by bouteillerAlan** [comment]
Hey, first FYI the full doc about each key contains on the `PKGBUILD` is available here : https://wiki.archlinux.org/title/PKGBUILD#validpgpkeys

The `validpgpkeys` must be put without the `"` : for example `validpgpkeys=(6A2ECC8A396F8A943A109A1E0F11C2A6BF79111E)`

Next you need to have your key available on the web, if it's not the case the validation doesn't work. The most simple way to do it is with [kleopatra](https://apps.kde.org/kleopatra/) (imo) it's available on all linux platform.

Also, all the empty key's like `depends=()` must be removed.

Hope this help :) if you need more help please [open a conv in here](https://github.com/bouteillerAlan/archupdate/discussions/new?category=q-a) and I can try to help you.
